### ISSUE TITLE
[BE] 스프링부트 이미지에 워킹 디렉토리 및 불륨 설정

### ISSUE THREAD

**Issue by yonghwankim-dev** [yonghwankim-dev/be-java-cafe-max#3]
- Dockerfile에 워킹 디렉토리 및 볼륨 설정합니다.
- 워킹 디렉토리의 의미 알기
- 워킹 디렉토리 및 볼륨 설정하고 실행하여 확인하기

**Comment by yonghwankim-dev** [comment]
### 워킹 디레토리 설정
#### Dockerfile

```Dockerfile
FROM openjdk:11
WORKDIR /app
ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","app.jar"]
```

#### docker-compose.yml

```yml
version: "3"
services:
  app:
    container_name: be-java-cafe-max
    image: yhkim951107/be-java-cafe-max
    ports:
      - 8080:8080
    volumes:
      - cafe_app:/app
volumes:
  cafe_app:
```
