### ISSUE TITLE
[BE] aappleboy/scp-action@master 복사 문제

### ISSUE THREAD

**Issue by yonghwankim-dev** [yonghwankim-dev/be-java-cafe-max#8]
### 배경
스프링부트 앱을 서버 배포하기 위해서 Github Actions, EC2 인스턴스를 이용하여 CI/CD 파이프 라인을 구축하려고 했습니다.

Github Actions를 수행하기 위해서 .github/workflows/cicd.yml 파일에 CI를 수행하기 위한 작업들을 정의하였습니다.

이 작업들 중에서 외부에 노출시키고 싶지 않은 설정 파일(데이터베이스 정보 등)들을 CI 과정에서 파일을 생성하여 시크릿 값으로 넣는 작업들이 있습니다.

다음은 문제가 발생한 워크플로우 파일 내용입니다.

```yml

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "네모네모", "main", "infra/cicd" ]
  pull_request:
    branches: [ "네모네모", "main", "infra/cicd" ]

permissions:
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ## JDK 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      # application-prod.properties 파일을 생성하여 설정
      - name: make application-prod.properties
        run: |
          cd ./src/main/resources
          touch ./application-prod.properties
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.properties
          ls -l
      # .env 파일을 생성하여 설정
      - name: make .env
        run: |
          touch ./.env
          echo "${{ secrets.DATASOURCE_ENV }}" > ./.env
          ls -l
      - name: make mysql config file
        run: |
          cd ./src/main/resources
          mkdir -p ./db/mysql/conf.d
          mkdir -p ./db/mysql/initdb.d
          touch ./db/mysql/conf.d/my.cnf
          touch ./db/mysql/initdb.d/init.sql
          echo "${{ secrets.MYSQL_CNF }}" > ./db/mysql/conf.d/my.cnf
          echo "${{ secrets.MYSQL_INIT }}" > ./db/mysql/initdb.d/init.sql
          ls -l ./db/mysql/conf.d/
          ls -l ./db/mysql/initdb.d/
      # gradlew 실행을 위해서 실행 권한을 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Gradle을 이용하여 빌드 수행
      - name: Build with Gradle
        run: ./gradlew build -x test
      # 도커 이미지 빌드하여 도커 허브에 푸시하기
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME}}/be-java-cafe-max:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/be-java-cafe-max:latest
  cd-pipeline:
    needs: build-image
    name: continuos deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: print pwd, ls
        run: |
          pwd
          ls -l
      - name: copy datasource env file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: ".env"
          target: "/home/ec2-user/"
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "/home/ec2-user/"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          port: 22
          script: |
            sudo chmod 666 /var/run/docker.sock
            docker stop $(docker ps -a -q) 2>/dev/null
            docker-compose pull && docker-compose up -d
```

문제가 발생한 부분은 다음 부분이었습니다.

```yml
  cd-pipeline:
    needs: build-image
    name: continuos deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # ...
      - name: copy datasource env file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: ".env"
          target: "/home/ec2-user/"
```

에러 내용은 다음과 같았습니다.
```
Run appleboy/scp-action@master
  with:
    host: ***
    username: ec[2](https://github.com/yonghwankim-dev/be-java-cafe-max/actions/runs/5461538057/jobs/9939705852#step:6:2)-user
    key: ***
    port: 22
    source: .env
    target: /home/ec2-user/
    timeout: [3](https://github.com/yonghwankim-dev/be-java-cafe-max/actions/runs/5461538057/jobs/9939705852#step:6:3)0s
    command_timeout: 10m
    use_insecure_cipher: false
    rm: false
    debug: false
    strip_components: 0
    overwrite: false
    tar_dereference: false
    tar_exec: tar
    proxy_port: 22
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
# ...
tar: empty archive
tar all files into /tmp/oKKbSiNQNq.tar.gz
exit status 1
```
에러의 내용은 EC2에 업로드할 대상 파일이 없다는 것이었습니다.

### 원인
- 본인은 Github Actions에서 워크플로우 단계를 2단계로 구분하였습니다. 첫번째 단계는 build-image, 두번째 단계는 continous deploy였습니다.
- 그런데 첫번째 단계 build-image에서 명령어로 생성한 시크릿 파일들은 continous deploy 단계에서는 공유가 되지 않는 것이었습니다. 왜냐하면 첫번째 단계에서 이어지는 것이 아닌 푸시한 커밋을 기준으로 새로운 브랜치를 생성하여 수행하기 때문입니다.

![image](https://github.com/yonghwankim-dev/be-java-cafe-max/assets/33227831/5d87736c-c7cc-4de7-aec4-23998f1a6f45)
- 실제로 continous deploy 단계에서 에러가 발생하기 이전 스텝에서 ls 명령어로 .env 파일이 있는지 확인해봤지만 없는 것을 확인할 수 있었습니다.

### 해결
- build-image, continous deploy 단계를 하나의 단계로 통합하여 해결하였습니다.

해결한 워크플로우 링크를 [참고](https://github.com/yonghwankim-dev/be-java-cafe-max/actions/runs/5461584756/workflow)해주세요.

### 개선점
- build-image, continous deploy 단계를 하나의 단계로 통합하여 해결할 수도 있지만 기존대로 각각의 단계로 나누고 continous deploy 단계에서 파일을 생성하는 스텝을 정의하여 EC2에 .env 파일을 복사하여 업로드하는 방법도 있습니다.
